### ISSUE TITLE
Provide intel builds

### ISSUE THREAD

**Issue by johnste** [johnste/finicky#367]

**Comment by masterflitzer** [comment]
just an idea, maybe consider building the releases in ci/cd (github actions), here's a list of available runners: <https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources>

you could use macos-latest for apple silicon & macos-13 for intel build, that way you don't have to worry about cross compilation and its complexity

idk if cross compiling is actually complex or not in this case, but this would be an easy way to achieve builds for both architectures and also a nice side effect would be that creating releases etc. is then automated, you'd only need to write the build workflow once and then use a [matrix job](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) that runs for each architecture, like so:

```yaml
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    strategy:
      matrix:
        runner: [macos-latest, macos-13]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
```
